# This file acts as the base configuration file for the project.
# See configs/template.yaml for an example how to create a deviating configuration file
# By default the config/user.yaml configuration file is used.

# used for logging
project_name: 'L-SARP'

# used for naming purposes
note: 'Language-based Scene Aware Robot Planner'

path_to_data: 'data/'


robot_planner_settings:
  active_scene: 'SEMANTIC_CORNER_WITH_BED' # needs to be in all caps, see misc/scenes_and_plugins_config.py
  task_instruction_mode: 'offline_predefined_instruction' # possible modes: "online_live_instruction", "offline_predefined_instruction"
  path_to_scene_data: 'data_scene/' # relative path to project_root_dir

# We give the robot task, and then the robot needs to great a goal, subtasks, and plan its actions to achieve the goal

robot_parameters:
  verbose: False

# device on which to train
device: 'cuda'

pre_scanned_graphs:
  base_fiducial_id: 52
  graph_frame_name_prefix: 'filtered_fiducial_'
  floor: -0.1
  low_res: '12_03_2025'
  high_res: '12_03_2025'
  draw_point_clouds: false # Set to true to enable point cloud visualization in the alignment script

# paths are relative from project_root_directory
subpaths:
  cache: 'cache/'

  logs: 'data/logs/'
  output: 'output/'
  resume_from: 'path/to/weights'
  data: 'data/'
  graphs: 'data/graphs/'
  prescans: 'data/prescans'
  autowalks: 'data/autowalk'
  point_clouds: 'data/point_clouds'
  aligned_point_clouds: 'data/aligned_point_clouds'
  masks: 'data/masked'
  # environment
  environment: '.environment.yaml'
  spot_description: 'spot_description'
  tmp: 'data/tmp'
  openmask_features: 'data/openmask_features'

servers:
  graspnet:
    ip: '127.0.0.1'
    port: 5000
    route: 'graspnet/predict'
  openmask:
    ip: '127.0.0.1'
    port: 5001
    route: 'openmask/save_and_predict'
  vitpose:
    ip: '127.0.0.1'
    port: 5002
    route: 'vitpose/predict'
  darknet:
    ip: '127.0.0.1'
    port: 5003
    route: 'darknet/predict'
  yolodrawer:
    ip: '127.0.0.1'
    port: 5004
    route: 'yolodrawer/predict'
